language: ruby
rvm:
  - 2.2.1
git:
  submodules: false
notifications:
  email:
    recipients:
      - wordman05@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
  - master
addons:
  apt:
    packages:
install:
  - bundle install
script:
  - echo 'Configuring JIT variables...'
  - sed 's/TRAVISCOMMIT/'$TRAVIS_COMMIT'/' builddata.partial.rb > builddata.partial2.rb
  - sed 's/TRAVISBUILD/'$TRAVIS_BUILD_NUMBER'/' builddata.partial2.rb > inc/builddata.rb
  - rm builddata.partial2.rb
  - head ./inc/builddata.rb
  # Begin testing
  - echo 'Beginning unit tests...'
  - rake
  - echo 'Unit testing is completed!'
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: xscout
  skip_cleanup: true
